---
postfix_configure_firewall: true

postfix_soft_bounce_enabled: false

postfix_queue_directory: /var/spool/postfix
postfix_command_directory: /usr/sbin
postfix_data_directory: /var/lib/postfix

postfix_mail_owner: postfix

postfix_myhostname: "{{ ansible_fqdn }}"
postfix_mydomain: "{{ ansible_domain if ansible_domain | default('') != '' else 'localdomain' }}"
postfix_myorigin: "{{ ansible_domain if ansible_domain | default('') != '' else 'localdomain' }}"

postfix_inet_interfaces_loopback_only: true
postfix_inet_interfaces_all: false
postfix_inet_protocols: all

postfix_mydestination:
  - $myhostname
  - localhost.$mydomain
  - localhost

postfix_unknown_local_recipient_reject_code: 550

postfix_mynetworks_style: host

postfix_mynetworks:
  - '127.0.0.0/8'

postfix_smtpd_recipient_restrictions:
  - permit_mynetworks
  - permit_sasl_authenticated
  - reject_unauth_destination
  - reject_invalid_hostname
  - reject_non_fqdn_hostname
  - reject_non_fqdn_sender
  - reject_non_fqdn_recipient
  - reject_unknown_sender_domain
  - reject_unknown_recipient_domain
  - reject_rbl_client sbl.spamhaus.org
  - reject_rbl_client cbl.abuseat.org
  - reject_rbl_client dul.dnsbl.sorbs.net
  - permit

postfix_smtpd_sender_restrictions:
  - reject_unknown_sender_domain

postfix_use_relay_recipient_map_file: false

postfix_in_flow_delay: 1s

postfix_use_alias_map_file: true
postfix_use_nis_alias_map: true
postfix_custom_alias_maps: []

postfix_use_header_checks_file: false
postfix_custom_header_checks: []

postfix_smtpd_banner: $myhostname ESMTP $mail_name

postfix_debug_peer_level: 2

postfix_sendmail_path: /usr/sbin/sendmail.postfix
postfix_newaliases_path: /usr/bin/newaliases.postfix
postfix_mailq_path: /usr/bin/mailq.postfix

postfix_setgid_group: postdrop

postfix_manpage_directory: /usr/share/man
postfix_sample_directory: /usr/share/doc/postfix/examples

postfix_smtpd_tls_mandatory_sslv2_enabled: false
postfix_smtpd_tls_mandatory_sslv3_enabled: false
postfix_smtpd_tls_mandatory_tlsv1_enabled: false
postfix_smtpd_tls_mandatory_tlsv1_1_enabled: false
postfix_smtpd_tls_mandatory_tlsv1_2_enabled: true
postfix_smtpd_tls_mandatory_tlsv1_3_enabled: true

postfix_smtpd_tls_sslv2_enabled: false
postfix_smtpd_tls_sslv3_enabled: false
postfix_smtpd_tls_tlsv1_enabled: false
postfix_smtpd_tls_tlsv1_1_enabled: false
postfix_smtpd_tls_tlsv1_2_enabled: true
postfix_smtpd_tls_tlsv1_3_enabled: true

postfix_smtp_tls_mandatory_sslv2_enabled: false
postfix_smtp_tls_mandatory_sslv3_enabled: false
postfix_smtp_tls_mandatory_tlsv1_enabled: false
postfix_smtp_tls_mandatory_tlsv1_1_enabled: false
postfix_smtp_tls_mandatory_tlsv1_2_enabled: true
postfix_smtp_tls_mandatory_tlsv1_3_enabled: true

postfix_smtp_tls_sslv2_enabled: false
postfix_smtp_tls_sslv3_enabled: false
postfix_smtp_tls_tlsv1_enabled: false
postfix_smtp_tls_tlsv1_1_enabled: false
postfix_smtp_tls_tlsv1_2_enabled: true
postfix_smtp_tls_tlsv1_3_enabled: true

postfix_smtpd_tls_enabled: false
postfix_smtpd_tls_security_level: may

postfix_smtp_tls_security_level: may

postfix_custom_main_cf: ''

postfix_aliases: []

postfix_smtp_listening_port: 25

postfix_master_process_config:
  - service: "{{ 'smtp' if postfix_smtp_listening_port | int == 25 else postfix_smtp_listening_port }}"
    type: inet
    private: false
    command: smtpd
  - service: pickup
    type: unix
    private: false
    wakeup_time: 60
    max_processes: 1
    command: pickup
  - service: cleanup
    type: unix
    private: false
    max_processes: 0
    command: cleanup
  - service: qmgr
    type: unix
    private: false
    wakeup_time: 300
    max_processes: 1
    command: qmgr
  - service: tlsmgr
    type: unix
    wakeup_time: 1000?
    max_processes: 1
    command: tlsmgr
  - service: rewrite
    type: unix
    command: trivial-rewrite
  - service: bounce
    type: unix
    command: bounce
  - service: defer
    type: unix
    max_processes: 0
    command: bounce
  - service: trace
    type: unix
    command: bounce
  - service: verify
    type: unix
    max_processes: 1
    command: verify
  - service: flush
    type: unix
    private: false
    wakeup_time: 1000?
    max_processes: 0
    command: flush
  - service: proxymap
    type: unix
    command: proxymap
  - service: proxywrite
    type: unix
    max_processes: 1
    command: proxymap
  - service: smtp
    type: unix
    command: smtp
  - service: relay
    type: unix
    command: smtp -o syslog_name=postfix/$service_name
  - service: showq
    type: unix
    private: false
    command: showq
  - service: error
    type: unix
    command: error
  - service: retry
    type: unix
    command: error
  - service: discard
    type: unix
    command: discard
  - service: local
    type: unix
    unprivileged: false
    command: local
  - service: virtual
    type: unix
    unprivileged: false
    command: virtual
  - service: lmtp
    type: unix
    command: lmtp
  - service: anvil
    type: unix
    max_processes: 1
    command: anvil
  - service: scache
    type: unix
    max_processes: 1
    command: scache
  - service: postlog
    type: unix
    private: false
    max_processes: 1
    command: postlogd
