---
- name: Rebuild aliases database
  listen: _postfix_rebuild_aliases
  become: true
  ansible.builtin.command: postalias /etc/aliases
  changed_when: true

- name: Restart Postfix
  listen: _postfix_restart_postfix
  become: true
  ansible.builtin.systemd_service:
    name: postfix.service
    state: restarted
